version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spingboot-with-likelion
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
  postgresql:
    ports:
    - "5432:5432"
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: duclong173
      POSTGRES_USER: postgres
      POSTGRES_DB: long

